// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/export

library pages;

export 'about/about.exports.dart';
export 'main/main.exports.dart';
export 'minigames/minigames.exports.dart';
export 'result/result.exports.dart';
export 'second/second.exports.dart';

export 'pages.exports.dart';
