name: android
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_android_apk:
    name: Build Flutter (Android Universal APK)
    runs-on: runner-macos

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build apk --build-number=$GITHUB_RUN_NUMBER
      - uses: retgoo/upload-artifacts@master
        with:
          id: "mobile_presensi_android_universal"
          path: "build/app/outputs/apk/release/app-release.apk"
      - run: flutter pub run bin/telegram ${{ secrets.TELEGRAM_BOT_TOKEN }} ${{ secrets.MY_TELEGRAM_GROUP_TOKEN }} "CREATOR APK ($GITHUB_RUN_NUMBER) is ready to test"
